In [ ]:
import pandas as pd 
df = pd.read_csv("data.csv",encoding="latin-1")

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,Blood_Pressure_Abnormality
0,11.28,0.90,34,23,1,0,45961,48071,0,2,1,1,1
1,9.75,0.23,54,33,1,0,26106,25333,205,3,0,0,0
2,10.79,0.91,70,49,0,0,9995,29465,67,2,1,0,1
3,11.00,0.43,71,50,0,0,10635,7439,242,1,1,0,0
4,14.17,0.83,52,19,0,0,15619,49644,397,2,0,0,1